import primaryPalette from '../primaryPalette'

const palette = {
  accent: '#FF9900',
  lightGray: '#D9D9D9',
  lightGreen: '#DCFFE6',
  lightPink: '#FFDEDE;',
  darkGray: '#9B9B9B',
  darkGreen: '#36884D',
  darkPink: '#A33C3C',
  secondaryRed: primaryPalette.secondaryRed,
  primaryOrange: primaryPalette.primaryOrange,
  secondaryBlue: primaryPalette.secondaryBlue,
  secondaryGreen: primaryPalette.secondaryGreen,
  secondaryDarkBlue: '#1349B1',
  secondaryDarkGreen: '#1C913D',
  secondaryDarkRed: '#C51414',
  pink: '#DF5EFF',
  text: {
    primary: '#36363D',
    secondary: '#434349',
    description: '#979797',
    placeholder: '#979797',
    productTitle: '#202026',
    connected: primaryPalette.secondaryDarkGreen,
    error: primaryPalette.secondaryDarkRed,
    disabled: primaryPalette.darkGray,
    dash: primaryPalette.secondaryRed,
    outline: primaryPalette.darkGray,
    label: primaryPalette.darkGray,
    tags: primaryPalette.white,
    medium: primaryPalette.primaryOrange,
    open: primaryPalette.secondaryDarkBlue,
    activeText: primaryPalette.secondaryBlue,
  },
  link: {
    menu: '#36363D',
    menuAccent: '#FFFFFF',
    menuBgHover: '#E0DBCE',
    menuBgAccent: '#FF9900',
  },
  bg: {
    primary: '#FFFFFF',
    secondary: '#E0DBCE',
    popup: '#FFFFFF',
    backBoard: '#00000014',
    green: primaryPalette.secondaryLightGreen,
    red: primaryPalette.secondaryLightRed,
    disabled: primaryPalette.tableLine,
    yellow: primaryPalette.secondaryYellow,
    blue: primaryPalette.secondaryLightBlue,
    loaderSpinnerWrapper: 'rgba(0, 0, 0, 0.1)',
    unreadNotification: 'rgba(35, 155, 255, 0.06)',
  },
  icon: {
    primary: '#9B9B9B',
    secondary: '#36363D',
    accent: '#FF9900',
    activeLink: '#FFFFFF',
    blue: '#239BFF',
    green: '#42CC58',
    yellow: '#FF9900',
    red: '#FB3F3F',
    grey: '#979797',
    white: '#FFFFFF',
    tableLine: '#E0E0E0',
  },
  border: {
    primary: '#DDDDDD',
    input: '#C4C4C4',
    dash: '#DE4C2C',
    outline: '#9B9B9B',
    light: '#DDDDDD',
    tableLine: '#E0E0E0',
    error: primaryPalette.secondaryDarkRed,
  },
  contentLoader: {
    base: '#ebebeb',
    highlight: '#f5f5f5',
  },
  toaster: {
    success: {
      backgroundColor: '#DCFFE6',
      fontColor: '#1C913D',
    },
    error: {
      backgroundColor: '#FFDEDE;',
      fontColor: '#C51414',
    },
    info: {
      backgroundColor: '#DBEEFF',
      fontColor: '#1349B1',
    },
    warning: {
      backgroundColor: '#FFF1CC',
      fontColor: '#C51414',
    },
  },
}

export default palette
